if GM.Characters then return end // Prevent autorefresh

local cindex = 0
local function increment()
    cindex = cindex+1
    return cindex-1
end

GM.Characters = {

    ["Deer Haunter"] = {
        model        = "models/monstermash/deer_haunter_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_deer.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_deer_haunter.mdl",
        gib_head     = "models/monstermash/gibs/head_deerhaunter.mdl",
        gib_armleft  = "models/monstermash/gibs/dh_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/dh_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/dh_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/dh_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/deerhaunter_top.mdl",
        gib_bottom   = "models/monstermash/gibs/deerhaunter_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_deerhaunter_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_deerhaunter.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_zombie", "wos_fn_dancemoves"},
        origin       = "Tazer Man's mind",
        trivia       = "Timothy D. Manning was once your average deer-headed, hook-handed child. He did well in school, was polite, and always ate his vegetables. Now he is a horrific being that stalks the day and night. He is so menacing that he makes even the most dreaded beings like Cthulhu say 'Yeah, that guy's alright.'",
        loves        = "Grass",
        hates        = "Cars",
        skins        = nil,
        index        = increment()
    },
     
    ["Witch"] = {
        model        = "models/monstermash/witch_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_witch.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_witch.mdl",
        gib_armleft  = "models/monstermash/gibs/witch_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/witch_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/witch_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/witch_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/witch_top.mdl",
        gib_bottom   = "models/monstermash/gibs/witch_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_witch_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_witch.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_disagree", "wos_fn_starpower"},
        origin       = "2000 B.C.",
        trivia       = "An old lady who once sent an army of evil after a little girl after being bitten by her dog.",
        loves        = "Calculators",
        hates        = "Water",
        skins        = {
                            Color(152, 60, 16, 255),
                            Color(92, 139, 35, 255),
                            Color(122, 48, 160, 255),
                            Color(143, 16, 16, 255),
                       },
        index        = increment()
    },    
     
    ["Vampire"] = {
        model        = "models/monstermash/vampire_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_vampire.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_vampire.mdl",
        gib_armleft  = "models/monstermash/gibs/vampire_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/vampire_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/vampire_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/vampire_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/vampire_top.mdl",
        gib_bottom   = "models/monstermash/gibs/vampire_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_vampire_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_bow", "wos_fn_intensity"},
        origin       = "Dracula (1897)",
        trivia       = "Possible descendants of Vlad Tepes, vampires are feared due to their constant thirst for human blood and dangerously good looking attire. ",
        loves        = "Blood",
        hates        = "Wet socks",
        skins        = {
                            {Color(30, 30, 30, 255),    Color(200, 200, 200, 255)},
                            {Color(0, 0, 0, 255),       Color(30, 30, 30, 255)},
                            {Color(30, 30, 30, 255),    Color(57, 19, 18, 255)},
                            {Color(65, 18, 36, 255),    Color(200, 200, 200, 255)}
                       },
        index        = increment()
    },
    
    ["Nosferatu"] = {
        model        = "models/monstermash/nosferatu_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_nosferatu.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_nosferatu.mdl",
        gib_armleft  = "models/monstermash/gibs/nosferatu_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/nosferatu_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/nosferatu_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/nosferatu_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/nosferatu_top.mdl",
        gib_bottom   = "models/monstermash/gibs/nosferatu_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_nosferatu_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_necktie", "wos_fn_orangejustice"},
        origin       = "Nosferatu, eine Symphonie des Grauens (1922)",
        trivia       = "Technically he goes by Count Orlok, but we figured that most of you playing this wouldn't be cultured enough to know any better.",
        loves        = "Flickering light switches",
        hates        = "Daylight",
        skins        = nil,
        index        = increment()
    },
 
    ["Skeleton"] = {
        model        = "models/monstermash/skeleton_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_DUST,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_skeleton.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_skeleton.mdl",
        gib_armleft  = "models/monstermash/gibs/sk_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/sk_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/sk_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/sk_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/skeleton_top.mdl",
        gib_bottom   = "models/monstermash/gibs/skeleton_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_skeleton_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_skeleton.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_skeleton.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_skeleton.mdl",
        gib_headsnd  = Sound("death/head_explosion_bone.wav"),
        taunt        = {"taunt_mm_laugh", "wos_fn_wiggle"},
        origin       = "Roughly 2.1 - 1.5 million years ago",
        trivia       = "Why should I bother writing trivia? Skeletons aren't real.",
        loves        = "Milk and Trumpets",
        hates        = "Dogs",
        skins        = {
                            Color(219, 215, 195, 255),
                            Color(205, 199, 165, 255),
                            Color(112, 107, 85, 255),
                            Color(103, 60, 45, 255),
                       },
        index        = increment()
    },
    
    ["Guest"] = {
        model        = "models/monstermash/guest_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_DUST,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_guest.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_guest.mdl",
        gib_armleft  = "models/monstermash/gibs/guest_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/guest_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/guest_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/guest_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/guest_top.mdl",
        gib_bottom   = "models/monstermash/gibs/guest_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_guest_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_guest.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_guest.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_guest.mdl",
        gib_headsnd  = Sound("death/head_explosion_bone.wav"),
        taunt        = {"taunt_mm_necktie", "wos_fn_twist"},
        origin       = "Like, any graveyard",
        trivia       = "Despite wearing the fanciest clothes, Guest walks the earth with a big hole in his heart. Due to his appearance, he has no body to go with to the prom. ",
        loves        = "Looking nice",
        hates        = "Formal attire",
        skins        = {
                            Color(26, 26, 26, 255),
                            Color(62, 64, 62, 255),
                            Color(86, 72, 54, 255),
                            Color(16, 24, 33, 255),
                            Color(47, 25, 19, 255),
                            Color(143, 148, 135, 255),
                       },
        index        = increment()
    },

    ["Scarecrow"] = {
        model        = "models/monstermash/scarecrow_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_HAY,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_scarecrow.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_scarecrow.mdl",
        gib_head     = "models/monstermash/gibs/head_scarecrow.mdl",
        gib_armleft  = "models/monstermash/gibs/scarecrow_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/scarecrow_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/scarecrow_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/scarecrow_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/scarecrow_top.mdl",
        gib_bottom   = "models/monstermash/gibs/scarecrow_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_scarecrow_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_scarecrow.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_scarecrow.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_scarecrow.mdl",
        gib_headsnd  = Sound("death/head_explosion_bone.wav"),
        taunt        = {"taunt_mm_scarecrow", "wos_fn_infinidab"},
        origin       = "Your grandma's backyard",
        trivia       = "Scarecrow's biggest desire in life is to obtain a brain, so he has joined the mash to slash it out of whoever stands in the way of him and his scythe.",
        loves        = "Corn",
        hates        = "Crows",
        skins        = nil,
        index        = increment()
    },
     
    ["Headless Horseman"] = {
        model        = "models/monstermash/headless_horseman_final.mdl",
        unlisted     = false,
        special	     = false,
        bloodtype    = BLOODTYPE_BLACK,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_hhm.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_hhm.mdl",
        gib_head     = "models/monstermash/gibs/head_hhm.mdl",
        gib_armleft  = "models/monstermash/gibs/hhm_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/hhm_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/hhm_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/hhm_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/hhm_top.mdl",
        gib_bottom   = "models/monstermash/gibs/hhm_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_hhm_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_hhm.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_hhm.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_hhm.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_salute", "wos_fn_takethel"},
        origin       = "The Legend of Sleepy Hollow  (1820)",
        trivia       = "A Hessian artilleryman who was killed during the Battle of White Plains in 1776. He was decapitated by an American cannonball, and the shattered remains of his head were left on the battlefield while his comrades hastily carried his body away. Eventually they buried him in the cemetery of the Old Dutch Church of Sleepy Hollow, from which each Halloween night he rises as a malevolent ghost, furiously seeking his lost head.",
        loves        = "Heads",
        hates        = "Heads",
        skins        = nil,
        index        = increment()
    },
    
    ["Frankenstein's Monster"] = {
        model        = "models/monstermash/stein_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_stein.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_stein.mdl",
        gib_head     = "models/monstermash/gibs/head_stein.mdl",
        gib_armleft  = "models/monstermash/gibs/stein_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/stein_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/stein_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/stein_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/stein_top.mdl",
        gib_bottom   = "models/monstermash/gibs/stein_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_stein_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_robot", "wos_fn_reanimated"},
        origin       = "Frankenstein (1818)",
        trivia       = "Not to be confused with his creator, Victor Frankenstein, this unnamed creature just wants to listen to violin music, but is constantly shunned for his develish appearance.",
        loves        = "Violins",
        hates        = "Sparks",
        skins        = {
                            {Color(70, 61, 51, 255),   Color(149, 153, 123, 255)},
                            {Color(39, 39, 39, 255),    Color(181, 171, 149, 255)}
                       },
        index        = increment()
    },
    
    ["Bride"] = {
        model        = "models/monstermash/bride_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_mummy.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_bride.mdl",
        gib_armleft  = "models/monstermash/gibs/bride_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/bride_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/bride_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/bride_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/bride_top.mdl",
        gib_bottom   = "models/monstermash/gibs/bride_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_bride_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_persistence", "wos_fn_electroshuffle"},
        origin       = "Bride of Frankenstein (1935)",
        trivia       = "We need more money, but hockey masks aren't popular yet. Hmm...",
        loves        = "Not being alive",
        hates        = "Arranged marriages",
        skins        = nil,
        index        = increment()
    },

    ["Mummy"] = {
        model        = "models/monstermash/mummy_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_mummy.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_mummy.mdl",
        gib_armleft  = "models/monstermash/gibs/mummy_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/mummy_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/mummy_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/mummy_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/mummy_top.mdl",
        gib_bottom   = "models/monstermash/gibs/mummy_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_mummy_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_zombie", "wos_fn_groovejam"},
        origin       = "450 - 250 BC",
        trivia       = "The wrapped remains of once powerful rulers of Ancient Egypt.",
        loves        = "Yu-Gi-Oh!",
        hates        = "Air",
        skins        = {
                            Color(187, 188, 175, 255),
                            Color(73, 65, 51, 255),
                       },
        index        = increment()
    },

    ["Zombie"] = {
        model        = "models/monstermash/zombie_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_zombie.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_zombie.mdl",
        gib_armleft  = "models/monstermash/gibs/zombie_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/zombie_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/zombie_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/zombie_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/zombie_top.mdl",
        gib_bottom   = "models/monstermash/gibs/zombie_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_zombie_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_zombie", "wos_fn_rambunctious"},
        origin       = "Night of the Living Dead (1968)",
        trivia       = "Re-Animated corpses who rise from their graves at nightfall to feast upon the living. Not to be confused with vampires, who also rise from their graves at nightfall to feast upon the living.",
        loves        = "Getting home from work and catching the start of his favorite movie on TV",
        hates        = "Being expected to dance to thriller",
        skins        = {
                            {Color(72, 69, 47, 255), Color(180, 159, 116, 255)},
                            {Color(55, 40, 46, 255), Color(130, 124, 77, 255)},
                            {Color(49, 52, 48, 255), Color(131, 122, 101, 255)},
                       },
        index        = increment()
    },
     
    ["Bloody Mary"] = {
        model        = "models/monstermash/bloody_mary_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_bm.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_bloodymary.mdl",
        gib_armleft  = "models/monstermash/gibs/bm_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/bm_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/bm_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/bm_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/bm_top.mdl",
        gib_bottom   = "models/monstermash/gibs/bm_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_bloodymary_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt = {"taunt_mm_laugh", "wos_fn_trueheart"},
        origin       = "20th century folklore",
        trivia       = "It is believed that if you utter her name while holding a candle in a dark bathroom, you will catch a glimpse of your future loved ones, or you might end up at the jaws of this demon.",
        loves        = "Children",
        hates        = "Watching how hard you can pee",
        skins        = nil,
        index        = increment()
    },

    ["Banshee"] = {
        model        = "models/monstermash/banshee_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_banshee.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_banshee.mdl",
        gib_armleft  = "models/monstermash/gibs/banshee_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/banshee_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/banshee_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/banshee_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/banshee_top.mdl",
        gib_bottom   = "models/monstermash/gibs/banshee_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_banshee_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_generic.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_zombie", "wos_fn_livinglarge"},
        origin       = "1380",
        trivia       = "A sort of goddess of death that observes one's relatives before they die. Kinda like the Shinigami from Death Note except without the Death Note or having anything to do with a Shinigami.",
        loves        = "Shrieking",
        hates        = "Final Destination characters",
        skins        = {
                            {Color(38, 66, 38, 255), Color(38, 42, 38, 255)},
                            {Color(43, 35, 50, 255), Color(128, 128, 128, 255)},
                            {Color(37, 40, 70, 255), Color(0, 0, 0, 255)},
                       },
        index        = increment()
    },
 
    ["Invisible Man"] = {
        model        = "models/monstermash/invisible_man_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_invisibleman.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_invisibleman.mdl",
        gib_armleft  = "models/monstermash/gibs/invisibleman_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/invisibleman_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/invisibleman_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/invisibleman_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/invisible_man_top.mdl",
        gib_bottom   = "models/monstermash/gibs/invisible_man_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_invisibleman_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_im.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_necktie", "wos_fn_poplock"},
        origin       = "The Invisible Man (1897)",
        trivia       = "An unhinged, yet brilliant scientist who had engineered the means to become invisibile. Not so much for reversing the process, however.",
        loves        = "John Cena",
        hates        = "Intrusive people",
        skins        = nil,
        index        = increment()
    },

    ["Mad Scientist"] = {
        model        = "models/monstermash/mad_scientist_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_scientist.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_scientist.mdl",
        gib_head     = "models/monstermash/gibs/head_madscientist.mdl",
        gib_armleft  = "models/monstermash/gibs/scientist_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/scientist_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/scientist_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/scientist_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/scientist_top.mdl",
        gib_bottom   = "models/monstermash/gibs/scientist_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_ms_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_ms.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_glass.wav"),
        taunt        = {"taunt_mm_laugh", "wos_fn_fresh"},
        origin       = "1962",
        trivia       = "He’s almost as smart as the Invisible Man, but not smart enough to invent invisibility. Hence why he is mad.",
        loves        = "Unorthodox medical procedures",
        hates        = "Lacking the ability to close his eyes",
        skins        = {
                            Color(186, 179, 122, 255),
                            Color(115, 200, 116, 255),
                            Color(153, 57, 8, 255),
                            Color(142, 0, 0, 255),
                            Color(123, 44, 162, 255),
                       },
        index        = increment()
    },
    
    ["Lagoon Creature"] = {
        model        = "models/monstermash/cbl_final.mdl",
        unlisted     = false,
        special      = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_cbl.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_generic.mdl",
        gib_head     = "models/monstermash/gibs/head_creatureblacklagoon.mdl",
        gib_armleft  = "models/monstermash/gibs/cbl_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/cbl_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/cbl_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/cbl_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/cbl_top.mdl",
        gib_bottom   = "models/monstermash/gibs/cbl_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_cbl_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_ms.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_persistence", "wos_fn_boneless"},
        origin       = "Creature from the Black Lagoon (1954)",
        trivia       = "Hiding in the depths of the jungle from the more evolved and sophisticated mankind, the \"gillman\" is known to become violent when threatened by intruders. He lurks within his swamp, living off the land unless provoked to pursue unsuspecting human women.",
        loves        = "Mackin' on hoes.",
        hates        = "Being fucking shot to death.",
        skins        = {
                            Color(90, 106, 120, 255),
                            Color(96, 108, 72, 255),
                            Color(116, 143, 107, 255)
                       },
        index        = increment()
    },
  
    ["Rex"] = {
        model        = "models/monstermash/rex_final.mdl",
        unlisted     = false,
        special      = true,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_rex.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_deer_haunter.mdl",
        gib_head     = "models/monstermash/gibs/head_rex.mdl",
        gib_armleft  = "models/monstermash/gibs/rex_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/rex_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/rex_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/rex_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/rex_top.mdl",
        gib_bottom   = "models/monstermash/gibs/rex_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_rex_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_rex.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_doittoem", "wos_fn_dancemoves"},
        origin       = "Some edgey loser's Steam profile",
        trivia       = "If he had a revolver with 2 bullets and he was in a room with Hitler and a stoner, he would shoot hitler twice cause he would beat the stoner to death with his own hands.",
        loves        = "Yiff",
        hates        = "Gamers",
        skins        = nil,
        index        = increment()
    },
    
    ["Random"] = {
        model        = "models/monstermash/random_character.mdl",
        unlisted     = false,
        origin       = "Unknown",
        trivia       = "Not much is known about Random. It is believed that it was created by lazy players who are unsure of who they want to be. Random can take many forms, which it has no control over.",
        loves        = "Ditto",
        hates        = "Existence",
        skins        = nil,
        index        = increment()
    },

    ["Kirito"] = {
        model        = "models/player/Kirito.mdl",
        unlisted     = true,
        special	     = false,
        bloodtype    = BLOODTYPE_NORMAL,
        gibs         = true,
        bifurcates   = true,
        decapitates  = true,
        c_arms       = "models/c_models/c_arms_mummy.mdl",
        gib_skeleton = "models/monstermash/gibs/fried_skeleton_deer_haunter.mdl",
        gib_head     = "models/monstermash/gibs/head_deerhaunter.mdl",
        gib_armleft  = "models/monstermash/gibs/dh_arm_left.mdl",
        gib_armright = "models/monstermash/gibs/dh_arm_right.mdl",
        gib_legleft  = "models/monstermash/gibs/dh_leg_left.mdl",
        gib_legright = "models/monstermash/gibs/dh_leg_right.mdl",
        gib_top      = "models/monstermash/gibs/deerhaunter_top.mdl",
        gib_bottom   = "models/monstermash/gibs/deerhaunter_lower.mdl",
        gib_stack    = "models/monstermash/gibs/gib_deerhaunter_full.mdl",
        gib_headbits = "models/monstermash/gibs/gib_headshot_deerhaunter.mdl",
        gib_chunks   = "models/monstermash/gibs/gib_chunks_generic.mdl",
        gib_torso    = "models/monstermash/gibs/torso_explosion_generic.mdl",
        gib_headsnd  = Sound("death/head_explosion_flesh.wav"),
        taunt        = {"taunt_mm_zombie", "wos_fn_dancemoves"},
        skins        = nil,
        index        = increment()
    },

}

GM.CharacterSpecials = {
    ["Rex"] = {
        "STEAM_0:0:31739525", // Buu342
        "STEAM_0:0:56188280", // Demo
        "STEAM_0:1:30535198", // Cougar Magnum
        "STEAM_0:0:28144880", // Rex Impaler
    }
}


print("/****************************")
print("Finished adding characters. Total: "..(#table.GetKeys(GM.Characters)))
print("****************************/")