MusicList = {
    {
        name = "2 SPOOKY 4 U",
        author = "Griffin Lewis",
        startingsong = "",
        song = "sound/music/2Spooky4U.ogg",
        dur_starting = 0,
        dur_song = 184.935,
    },
    {
        name = "Danse Macabre",
        author = "Camille Saint-saëns",
        startingsong = "",
        song = "sound/music/DanseMacabre.ogg",
        dur_starting = 0,
        dur_song = 425.205,
    },
    {
        name = "Goosebumps Theme (Cover)",
        author = "Samuel Fu",
        startingsong = "",
        song = "sound/music/Goosebumps.ogg",
        dur_starting = 0,
        dur_song = 61.621,
    },    
    {
        name = "Grim Grinning Ghosts",
        author = "Xavier Atencio",
        startingsong = "",
        song = "sound/music/GrimGrinningGhosts.ogg",
        dur_starting = 0,
        dur_song = 59.720,
    },
    {
        name = "Halloween Theme",
        author = "John Carpenter",
        startingsong = "",
        song = "sound/music/Halloween.ogg",
        dur_starting = 0,
        dur_song = 165.325,
    },
    {
        name = "Haunted House",
        author = "Chris Kevin",
        startingsong = "",
        song = "sound/music/HauntedHouse.ogg",
        dur_starting = 0,
        dur_song = 125.032,
    },
    {
        name = "House on Haunted Hill",
        author = "Frank DeVol",
        startingsong = "",
        song = "sound/music/hauntedhill.ogg",
        dur_starting = 0,
        dur_song = 138.01,
    },
    {
        name = "Majin Castle Part 1",
        author = "Konami",
        startingsong = "sound/music/MajinCastle1-1.ogg",
        song = "sound/music/MajinCastle1-2.ogg",
        dur_starting = 3.176,
        dur_song = 50.276,
    },
    {
        name = "Majin Castle Part 2",
        author = "Konami",
        startingsong = "",
        song = "sound/music/MajinCastle2.ogg",
        dur_starting = 0,
        dur_song = 44.006,
    },
    {
        name = "Midnight in a Madhouse",
        author = "Chick Webb",
        startingsong = "",
        song = "sound/music/madhouse.ogg",
        dur_starting = 0,
        dur_song = 146.01,
    },
    {
        name = "Monster Mash",
        author = "Bobby Pickett",
        startingsong = "",
        song = "sound/music/MonsterMash.ogg",
        dur_starting = 0,
        dur_song = 184.98,
    },
    {
        name = "More Ghosts 'n Stuff",
        author = "deadmau5",
        startingsong = "",
        song = "sound/music/ghostsnstuff.ogg",
        dur_starting = 0,
        dur_song = 376.01,
    },
    {
        name = "Mystic Mansion",
        author = "Naofumi Hataya & Jun Senoue",
        startingsong = "",
        song = "sound/music/mystic.ogg",
        dur_starting = 0,
        dur_song = 163.01,
    },
    {
        name = "Party Ghouls",
        author = "Mat Clark",
        startingsong = "",
        song = "sound/music/PartyGhoul.ogg",
        dur_starting = 0,
        dur_song = 195.01,
    },
    {
        name = "Scared Stupid Intro Theme",
        author = "Bruce Arnston and Kirby Shelstad",
        startingsong = "",
        song = "sound/music/stupid.ogg",
        dur_starting = 0,
        dur_song = 126.01,
    },
    {
        name = "Scary Godmother Theme",
        author = "Valhalla Wind Band",
        startingsong = "",
        song = "sound/music/sgm1.ogg",
        dur_starting = 0,
        dur_song = 54.01,
    },
    {
        name = "Scary Godmother Party Music",
        author = "J.W.",
        startingsong = "",
        song = "sound/music/sgm2.ogg",
        dur_starting = 0,
        dur_song = 154.01,
    },
    {
        name = "Spooky Scary Skeletons (Eurobeat)",
        author = "Equinox Eurobeat",
        startingsong = "",
        song = "sound/music/Equinox.ogg",
        dur_starting = 0,
        dur_song = 109.374,
    },
    {
        name = "Skeleton in the Closet",
        author = "Artie Shaw",
        startingsong = "",
        song = "sound/music/skeletoncloset.ogg",
        dur_starting = 0,
        dur_song = 162.01,
    },
    {
        name = "Spooky Scary Skeletons (Piano)",
        author = "grande1899",
        startingsong = "",
        song = "sound/music/SpookyScaryPiano.ogg",
        dur_starting = 0,
        dur_song = 134.441,
    },
    {
        name = "The Great Doot Doot Sneak",
        author = "Julian Cianciolo",
        startingsong = "",
        song = "sound/music/DootDoot.ogg",
        dur_starting = 0,
        dur_song = 124.01,
    },
    {
        name = "The Little Man Who Wasn't There",
        author = "Glenn Miller",
        startingsong = "",
        song = "sound/music/littleman.ogg",
        dur_starting = 0,
        dur_song = 182.01,
    },
    {
        name = "The Monster Hop",
        author = "Bert Convy",
        startingsong = "",
        song = "sound/music/monsterhop.ogg",
        dur_starting = 0,
        dur_song = 147.01,
    },
    {
        name = "The Night Before Halloween",
        author = "Bill Buchanan",
        startingsong = "",
        song = "sound/music/nbh.ogg",
        dur_starting = 0,
        dur_song = 125.01,
    },
    {
        name = "The Old Devil King",
        author = "Thierry Laurent Caroubi",
        startingsong = "",
        song = "sound/music/devil.ogg",
        dur_starting = 0,
        dur_song = 168.01,
    },
    {
        name = "Theme from Friday the 13th Part 3",
        author = "Harry Manfredini",
        startingsong = "",
        song = "sound/music/F13Part3.ogg",
        dur_starting = 0,
        dur_song = 165.972,
    },       
    {
        name = "This Is Halloween (Instrumental)",
        author = "Danny Elfman",
        startingsong = "",
        song = "sound/music/nbc.ogg",
        dur_starting = 0,
        dur_song = 192.01,
    },   
    {
        name = "Thriller (Cover)",
        author = "Halloween Sound Machine",
        startingsong = "",
        song = "sound/music/Thriller.ogg",
        dur_starting = 0,
        dur_song = 344.436,
    },    
    {
        name = "White Shivers",
        author = "New Orleans Owls",
        startingsong = "",
        song = "sound/music/shivers.ogg",
        dur_starting = 0,
        dur_song = 166.01,
    }, 
}