AddCSLuaFile()

surface.CreateFont( "MMDefaultFont", { 
	font = "Chiller",
	extended = false,
	size = ScreenScale(20),
	weight = 700,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMDefaultFont_noscale", {
	font = "Chiller",
	extended = false,
	size = 48,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMFriday13", {
	font = "Friday13",
	extended = false,
	size = ScreenScale(16),
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMVersion", {
	font = "Courier",
	extended = false,
	size = ScreenScale(10),
	weight = 1000,
	blursize = 0,
	scanlines = 0,
	antialias = false,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = true ,
})

surface.CreateFont( "MMCredits", {
	font = "Arial Black",
	extended = false,
	size = ScreenScale(6),
	weight = 1000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = true,
})

surface.CreateFont( "MMTabs", {
	font = "Chiller",
	extended = false,
	size = ScreenScale(15),
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMMenuStory", {
	font = "Chiller",
	extended = false,
	size = ScreenScale(9.5),
	weight = 600,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMCostFont", {
	font = "Chiller",
	extended = false,
	size = ScreenScale(9),
	weight = 600,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMMenuControls", {
	font = "Times New Roman",
	extended = false,
	size = ScreenScale(6.5),
	weight = 1000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMCharacterDesc", {
	font = "Times New Roman",
	extended = false,
	size = ScreenScale(7),
	weight = 1000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})

surface.CreateFont( "MMScoreboardFont", { 
	font = "Chiller",
	extended = false,
	size = ScreenScale(15),
	weight = 700,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false ,
})